apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name:get-shop-info
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
            args:
            - --trigger-config=/app/config/deployer-trigger.yaml
